post http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Ddd",
    "name": "user4",
    "password": "123456"
}

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRkZCIsImlkIjoiNWY2NzA5Yjk5NjUyZjgzNDQ4NmJmOTdlIiwiaWF0IjoxNjAwNTg4MjM2fQ.vpFMJ0kVlAfLilmnU2BKvXrhlxL0QHpqF1r9VDkEDVg
5f6709b99652f834486bf97e
